base_images:
  base:
    name: "4.15"
    namespace: origin
    tag: base
  base-rhel9:
    name: "4.15"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.21-openshift-4.15:
    name: builder
    namespace: ocp
    tag: ocp_builder_rhel-9-golang-1.21-openshift-4.15
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile.okd
  from: base-rhel9
  inputs:
    ocp_builder_rhel-9-golang-1.21-openshift-4.15:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.20-openshift-4.15
  to: operator-marketplace
promotion:
  to:
  - name: "4.15"
    namespace: origin
releases:
  initial:
    integration:
      name: "4.15"
      namespace: origin
  latest:
    integration:
      include_built_images: true
      name: "4.15"
      namespace: origin
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-gcp
  optional: true
  steps:
    cluster_profile: gcp
    workflow: openshift-e2e-gcp
zz_generated_metadata:
  branch: release-4.15
  org: operator-framework
  repo: operator-marketplace
  variant: okd
