branch-protection:
  orgs:
    operator-framework:
      repos:
        operator-controller:
          branches:
            main:
              protect: true
              required_status_checks:
                contexts:
                - e2e-kind
                - unit-test-basic
                - goreleaser
                - lint
                - verify-e2e
                - extension-developer-e2e
                - upgrade-e2e
                - go-apidiff
tide:
  merge_method:
    operator-framework/operator-controller: squash
  queries:
  - includedBranches:
    - main
    labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    repos:
    - operator-framework/operator-controller
